app:
  ingress:
    hosts:
      - host: "repl.prd.aepps.com"
        paths:
          - path: "/"
      - host: "repl.aepps.com"
        paths:
          - path: "/"
      - host: "repl.aeternity.io"
        paths:
          - path: "/"
    tls:
      - hosts:
          - "repl.aepps.com"
          - "repl.aeternity.io"
          - "repl.prd.aepps.com"
        secretName: aerepl-http-cert
