app:
  image:
    repository: aeternity/mdw-frontend
    pullPolicy: "Always"
    tag: "latest"
  
  resources:
    limits:
      memory: 288Mi
    requests:
      cpu: 200m
      memory: 288Mi
      
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
  env:
    "NUXT_APP_NODE_URL": "https://mainnet.aeternity.io/v3"
    "NUXT_APP_NODE_WS": "wss://mainnet.aeternity.io/mdw/websocket"
    "NUXT_APP_MDW_URL": "https://mainnet.aeternity.io/mdw"
    "NUXT_APP_OTHER_DEPLOYMENTS": "TESTNET@https://explorer.testnet.aeternity.io"
    "NUXT_APP_NETWORK_NAME": "MAINNET"
    "NUXT_APP_ENABLE_FAUCET": "false"
