app:
  ingress:
    hosts:
      - host: "contracts.prd.aepps.com"
        paths:
          - path: "/"
      - host: "contracts.aepps.com"
        paths:
          - path: "/"
    tls:
      - hosts:
        - "contracts.aepps.com"
        - "contracts.prd.aepps.com"
        secretName: aepp-contracts-cert
