app:
  secrets:
    external:
      remotePrefix: /k8s/prd-0e9c
  ingress:
    tls:
      - hosts:
          - "ga-multisig-backend-mainnet.prd.aepps.com"
        secretName: ga-multisig-backend-mainnet-cert
    hosts:
      - host: "ga-multisig-backend-mainnet.prd.aepps.com"
        paths:
          - path: "/"
  env:
    "PG_HOST": "superheroprd.cxhy2i9at0vj.eu-central-1.rds.amazonaws.com"
  versions:
    - {version: "main", gitSha: "3932d71"}
