app:
  ingress:
    hosts:
      - host: "aescan-frontend-mvp.prd.aepps.com"
        paths:
          - path: "/"
    tls:
      - hosts:
          - "aescan-frontend-mvp.prd.aepps.com"
          - "master-aescan-frontend-mvp.prd.aepps.com"
        secretName: aescan-frontend-mvp-cert
  image:
    tag: 0.4.0
  env:
    "NUXT_PUBLIC_APP_DOMAIN": "aescan-frontend-mvp.prd.aepps.com"
    "NUXT_PUBLIC_SENTRY_DSN": "https://ca073f3a8941437ea8726ac0b5617841@sentry.dev.service.aepps.com/3"
    "NUXT_PUBLIC_NETWORK_NAME": "MAINNET"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://mainnet.aeternity.io/mdw"
    "NUXT_PUBLIC_NODE_URL": "https://mainnet.aeternity.io/v3"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://mainnet.aeternity.io/mdw/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://aescan-frontend-mvp-testnet.prd.aepps.com"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-mainnet.prd.aepps.com"
