app:
  env:
    "NUXT_PUBLIC_NETWORK_NAME": "Mainnet"
    "NUXT_PUBLIC_MIDDLEWARE_URL": "https://mainnet.aeternity.io/mdw"
    "NUXT_PUBLIC_NODE_URL": "https://mainnet.aeternity.io/v3"
    "NUXT_PUBLIC_WEBSOCKET_URL": "wss://mainnet.aeternity.io/mdw/websocket"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_NAME": "TESTNET"
    "NUXT_PUBLIC_ALTERNATIVE_NETWORK_URL": "https://develop-aescan-frontend-mvp-testnet.dev.aepps.com"
    "NUXT_PUBLIC_DEX_BACKEND_URL": "https://dex-backend-mainnet.prd.aepps.com"
  ingress:
    hosts:
      - host: "aescan-frontend-mvp.stg.aepps.com"
        paths:
          - path: "/"
      - host: "pr-250-aescan-frontend-mvp.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-250"
      - host: "pr-253-aescan-frontend-mvp.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-253"
      - host: "pr-254-aescan-frontend-mvp.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-254"
      - host: "pr-256-aescan-frontend-mvp.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-256"
      - host: "pr-262-aescan-frontend-mvp.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-262"
      - host: "pr-263-aescan-frontend-mvp.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-263"
      - host: "pr-269-aescan-frontend-mvp.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-269"
  versions:
    - version: "pr-256"
      gitSha: "null"
    - version: "pr-240"
      gitSha: "13d0e9e"
    - version: "pr-254"
      gitSha: "8fdf516"
    - version: "pr-253"
      gitSha: "b22c0fb"
    - {version: "pr-262", gitSha: "232815b"}
    - {version: "pr-250", gitSha: "67a58a1"}
    - {version: "pr-269", gitSha: "09bd939"}
    - {version: "pr-263", gitSha: "bae0166"}
