app:
  ingress:
    hosts:
      - host: "state-channel-demo-backend.dev.aepps.com"
        paths:
          - path: "/"
      - host: "develop-state-channel-demo-backend.dev.aepps.com"
        paths:
          - path: "/"
            version: "develop"
  versions:
    - {version: "develop", gitSha: "3c160c5"}
  env:
    "NODE_ENV": "production"
